# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  save_interval: 50
  save_interval_updates: 10000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer

task:
  _name: grapheme_to_phoneme
  gdata: ???
  pdata: ???
  glabels: txt
  plabels: txt
  normalize: false
  gpad_idx: 1
  p2g_ratio: -1
  source_dictionary_path: ???
  target_dictionary_path: ???
  max_position: 2048

dataset:
  num_workers: 6
  max_tokens: 32000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: 10000
  validate_interval: 5
  valid_subset: dev

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 2

criterion:
  _name: ctc
  zero_infinity: true
  post_process: none

optimization:
  max_update: 50000
  lr: [0.00005]
  sentence_avg: true
  update_freq: [4]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: roberta_ft
  roberta_path: ???
  vocab_size: 500
  freeze_finetune_updates: 10000
  upsamp_kernel_size: 10
  upsamp_stride: 10
  upsamp_padding: 0
